task.spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Internl/abc/main/hubtop.lua"))()
        end)
task.spawn(function()
    loadstring(game:HttpGet("loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/PetSimulator99/main/redz9999.lua"))()", true))()
        end)
